name: Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: npm
          
      - name: Install dependencies
        run: npm install
        
      - name: Build website
        run: npm run build
      
      - name: Set Artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'build/'
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      contents: write
      id-token: write
      
    steps:
      - name: Deploy to GitHub Page
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
